version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./vite-vue-ts:/app
    ports:
      - "5173:5173"
